# Generated by Django 3.2.8 on 2022-12-25 11:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('amount_loan', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10000'))])),
                ('amount_to_repay', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10000'))])),
                ('amount_lated_repay', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('loan_date', models.DateField()),
                ('loan_repayment_date', models.DateField()),
                ('interest_rate', models.IntegerField(choices=[(0, 'INTEREST_RATE_MONTH_LOAN'), (1, 'INTEREST_RATE_MORE_THAN_ONE_MONTH_LOAN')], default=0)),
                ('number_lated_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mod_members.member')),
                ('valideted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
