# Generated by Django 3.2.8 on 2022-12-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generateNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('year', models.BooleanField(default=True)),
                ('month', models.BooleanField(default=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('last_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('prefix', 'year', 'month'),
            },
        ),
    ]
