# Generated by Django 3.2.8 on 2022-12-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('kind_identity', models.IntegerField(choices=[(0, 'ID Card'), (1, 'Passeport Card')], default=0, verbose_name='kind of identity')),
                ('identity_number', models.CharField(max_length=50, unique=True)),
                ('identity_delivery_date', models.DateField(blank=True, null=True)),
                ('identity_delivery_location', models.CharField(max_length=50, null=True)),
                ('nationality', models.CharField(choices=[('Burundian', 'Burundian'), ('Rwandan', 'Rwandan'), ('Tanzanian', 'Tanzanian'), ('Ugandan', 'Ugandan'), ('Kenyan', 'Kenyan'), ('Congolese', 'Congolese')], max_length=50)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'ordering': ('registration_number',),
            },
        ),
    ]
