# Generated by Django 3.2.8 on 2022-12-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
